baseURL: "https://abhimanyubabbar.github.io/"
languageCode: "en-us"
title: "Blog"
theme: "cupper-hugo-theme"

menu:
  nav:
    - name: Home
      url: /
      weight: 1

    - name: Posts
      url: /posts/
      weight: 2
